### PR TITLE
feat: adds AutoDiscover sensors for HomeAssistant

### PR DESCRIPTION
**Pull request by pmfernandes**
Following this discussion https://github.com/philibertc/micronova_controller/discussions/15 and because I used to create my MQTT sensors like this, I decided to open this PR to enable it.

@philibertc can you please review it and suggest changes?

The device "Micronova Controller" will be available under MQTT integration:
image

The final result of the entities is:
image

### CODE REVIEW

**Review by philibertc — APPROVED** [review]
That seems well integrated

**Comment by pmfernandes** [comment]
> That seems well integrated

You may merge it if you want.

**Comment by philibertc** [comment]
Hello, I will for sure
I would just like to test before merge.

**Comment by geraldFS** [comment]
Great!

good job
Bildschirmfoto_2022-12-11_10-48-25

**Pull request merged**
